### ISSUE TITLE
gsw_steric_height: web typo and Q on return value

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-R#38]
Prescript -- I tried emailing the below to Paul by sending to help@teos-10.org but the email bounced, stating that paul.barker@unsw.edu.au was an "Unrouteable address" and classifying that as a "Permanent error".  

My questions relate to how the base routine works (in C) ... this is therefore not really a question about GSW-R, per se, because in R we just wrap the C functions according to documentation (and with test values) on the TEOS-10 website.

1. A typo: the function named `gsw_geo_strf_steric_height()` is defined at the URL http://www.teos-10.org/pubs/gsw/html/gsw_steric_height.html and the title on the first line of that URL says “gsw_steric_height”.

2. A question: what is the function actually calculating? The docs suggest an integral (and that’s the usual definition in the literature) but the returned value (even in the test case on the above-named URL) is a vector, so I’m not quite sure what this means.  To get the integral, do I take the first value in that vector, the last, a sum, … ?

**Comment by dankelley** [comment]
PB and I have have entered into a discussion of this, over private email. I'll provide a suitable summary when I close the issue.

**Comment by dankelley** [comment]
Fixed

**Comment by richardsc** [comment]
For completeness, a summary?

**Comment by dankelley** [comment]
Sorry ... the summary is that the webpages got fixed, and that the function returns a vector of something similar to dynamic height, calculated to each of the pressures in turn. The unit of the returned value is m^2/s^2, and to convert its value to metres, divide by the acceleration due to gravity. (I am not 100% sure whether to use the local gravity or a constant value, and think that the only way to know for sure is to examine the underlying C code.)

As with all of GSW-R, users are asked to study the online docs for the matlab code. There are links there to further documentation, also.

Issue #39 has some followup on the limitations of the gsw code, and these limitations are now considered in the `oce` function `swDynamicHeight` (which is in a whole other repo, and thus shouldn't be discussed here ... except to say that I still want to think some more about it).

**Comment by efiring** [comment]
It is a geopotential anomaly, named here as "geostrophic streamfunction".  There is no need to convert it to meters for geostrophic calculations; the geostrophic velocity averaged between two stations, on a given pressure and relative to a common reference pressure, is just the difference in this streamfunction or geopotential anomaly, divided by the product of the distance between the stations and the mean coriolis parameter.  (That's actually assuming there is little change in coriolis parameter between the two stations; otherwise the structure of the currents between the stations comes into play.)
