### ISSUE TITLE
O2 functions not included in GSW-R

### ISSUE THREAD

**Issue by richardsc** [TEOS-10/GSW-R#52]
I noticed while doing some work with the python version of gsw that there are some O2 functions that appear to be included in GSW-C but that we haven't imported, e.g. `gsw_o2sol` and `gsw_o2sol_sp_pt`.

I thought that anything included in the GSW-C source was included in GSW-R, but perhaps that's not the case?

**Comment by dankelley** [comment]
Maybe the C source got updated.  I'll check on the weekend.

**Comment by dankelley** [comment]
Yes, I see them in the present version of the C code (as contained in GSW-R).  I'll add wrappers on the weekend.  Possibly I'll try updating the C code also, if there are documented changes.
```
gsw_oceanographic_toolbox.c:6420:function gsw_o2sol(sa, ct, p, lon, lat)
gsw_oceanographic_toolbox.c:6440:! gsw_o2sol : olubility of oxygen in micro-moles per kg          [umol/kg]
gsw_oceanographic_toolbox.c:6443:gsw_o2sol(double sa, double ct, double p, double lon, double lat)
gsw_oceanographic_toolbox.c:6446:    double sp, pt, pt68, x, y, o2sol,
gsw_oceanographic_toolbox.c:6469:    o2sol = exp(a0 + y*(a1 + y*(a2 + y*(a3 + y*(a4 + a5*y))))
gsw_oceanographic_toolbox.c:6472:    return o2sol;
gsw_oceanographic_toolbox.c:6477:function gsw_o2sol_sp_pt(sp, pt)
gsw_oceanographic_toolbox.c:6494:! gsw_o2sol_sp_pt : olubility of oxygen in micro-moles per kg     [umol/kg]
gsw_oceanographic_toolbox.c:6497:gsw_o2sol_sp_pt(double sp, double pt)
gsw_oceanographic_toolbox.c:6500:    double pt68, x, y, o2sol,
gsw_oceanographic_toolbox.c:6521:    o2sol = exp(a0 + y*(a1 + y*(a2 + y*(a3 + y*(a4 + a5*y))))
gsw_oceanographic_toolbox.c:6524:    return o2sol;
gswteos-10.h:177:extern double gsw_o2sol(double sa, double ct, double p, double lon, double lat);
gswteos-10.h:178:extern double gsw_o2sol_sp_pt(double sp, double pt);
```

**Comment by efiring** [comment]
Functions added:

https://github.com/TEOS-10/GSW-C/pull/26
https://github.com/TEOS-10/GSW-C/pull/30

Eric

**Comment by dankelley** [comment]
Thanks, Eric.  I've updated my GSW-C to the latest ([GSW-C/bad2c9e4e154597ce563aaaf3ce09b1c52a2ab46)](https://github.com/TEOS-10/GSW-C/commit/bad2c9e4e154597ce563aaaf3ce09b1c52a2ab46) and start from there.  This work normally doesn't take very long, and I'll likely do it over the weekend.

It won't get into [CRAN](https://cran.r-project.org/web/packages/gsw/index.html) until January, though, because I'd want it to be used by @richardsc and myself for a while before contemplating a submission to CRAN.  Plus, CRAN has a time-out during the solstice break.  But, since no user has been needing it for their work, it will be fine to wait a few weeks for a possible CRAN submission.

Thanks to Clark for noticing this and Eric for his very rapid comment.

**Comment by dankelley** [comment]
Oh, I see that the only difference from the most recent `GSW-C/gsw_oceanographic_toolbox.c` and `GSW-R/src/gsw_oceanographic_toolbox.c` is in the correction of some spelling errors in comments.  

Therefore, we don't have to worry about any user getting confused by new results coming from any of the presently-provided functions.  That's good, because static formulae are useful, at least in my mind...

... one of the things that worried me in the early days of TEOS10, when the idea was that the spatial database would be updated frequently, was that papers would have phrases like "SA was calculated using TEOS_yyyy-mm-dd".  That would mean that readers might have to convert to other formula to compare results ... a bit like in the days, when Paris had one version of the inch, London had another, etc.

**Comment by dankelley** [comment]
@richardsc I am seeing just 2 functions to add (below).  Are there others that you noticed?  (I see that you said 'e.g.' in your starting comment, so maybe you are aware of others.)
```
➜  src git:(develop) ✗ git grep -i o2|grep func
gsw_oceanographic_toolbox.c:function gsw_o2sol(sa, ct, p, lon, lat)
gsw_oceanographic_toolbox.c:function gsw_o2sol_sp_pt(sp, pt)
```

**Comment by richardsc** [comment]
No, that's probably it. I just didn't want to assume they were the only two before I'd had a chance to do an exhaustive search.

Thanks!

**Comment by efiring** [comment]
Is the salinometer function already in R?  It was added  to the C (and the Python) shortly after the 2 oxygen functions, in https://github.com/TEOS-10/GSW-C/pull/30.

**Comment by dankelley** [comment]
I've added the two O2 functions in "develop" commit 1525b9ff31060ac816dd120b511f5410e9fc6ead (along with tests, of course).

**Comment by dankelley** [comment]
I hadn't realized that this was still open.  Perhaps @richardsc can have a look and see whether to close it.

**Comment by richardsc** [comment]
I was just looking at this issue! Looks good!
