### ISSUE TITLE
Oxygen functions missing from R package?

### ISSUE THREAD

**Issue by FDylanT** [TEOS-10/GSW-R#57]
It appears that the `gsw_O2sol()` and `gsw_O2sol_sp_pt()` functions that exist in MATLAB aren't included in the R version of the gsw package (at least based on the [Reference](https://teos-10.github.io/GSW-R/reference/index.html) page) -- is this just a version issue on my end, or would there be scope to add them?

**Comment by dankelley** [comment]
These are available in the "develop" branch on github, which may be installed with `install_github()`.  This requires compilation, though, so if you are not able to do this, we could consider making a new update to the package.  We don't tend to make those updates very often, partly because CRAN does not favour frequent updates.

If you can work with the github version, I suggest you do that and see whether for example the docs make sense.

If you look at #52, you'll see the change we made to incorporate these oxygen functions.  Note letter-case in the names.

**Comment by dankelley** [comment]
FYI the changes from the 1.0-6 on CRAN to 1.0-7 in the "develop" branch are summarized at https://github.com/TEOS-10/GSW-R/blob/develop/NEWS.md

**Comment by dankelley** [comment]
I'm closing this because the code is updated on CRAN (it may be a few days for CRAN to build up binary packages for all platforms).
