### ISSUE TITLE
Add more documentation to @seealso sections

### ISSUE THREAD

**Issue by richardsc** [TEOS-10/GSW-R#8]
This issue is just to serve as a reminder, and, if I have the time at some point, to troll through the list and plan out which functions should be cross-referenced.

**Comment by dankelley** [comment]
I think this is great now, after the two editing passes we've had in the past couple of days. I don’t think it’s critical that the readalso items be detailed and complete, because the whole point is that we are leaving the task of learning the gsw functions up to the user. After all, the teos10 website provides a complete range of white papers and peer-reviewed articles for people wanting to learn the concepts, and the online Matlab documentation provides a great deal of detail at the function level.
